Hi there,

Some exception occured in the ricer bot.

<%= @exception.to_s %>

<%= @exception.backtrace.join("\n")  %>
